In [1]:
import numpy as np

np.set_printoptions(suppress=True)

In [3]:
A = np.array([[2,3],[5,7],[11,13]])
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [5]:
U, D, V = np.linalg.svd(A)
print("U")
print(U)
print("D")
print(D)
print("V")
print(V)

U
[[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]
D
[19.40321383  0.71783924]
V
[[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


In [6]:
D_seudo = np.zeros((A.shape[0],A.shape[1])).T
print(D_seudo)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print("Valores a reemplazar en D_pseudo")
print(D_seudo[:D.shape[0],:D.shape[0]])

In [7]:
print("Valores que pondremos en D_pseudo")
print(np.linalg.inv(np.diag(D)))

Valores que pondremos en D_pseudo
[[0.05153785 0.        ]
 [0.         1.39306957]]


In [8]:
print("D_pseudo")
D_seudo[:D.shape[0],:D.shape[0]] = np.linalg.inv(np.diag(D))
print(D_seudo)

D_pseudo
[[0.05153785 0.         0.        ]
 [0.         1.39306957 0.        ]]


In [9]:
A_pseudo = V.T.dot(D_seudo).dot(U.T)
print(A_pseudo)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [11]:
A_pse_calc = np.linalg.pinv(A)
print(A_pse_calc)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]
